server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistemaeducativo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      type: servlet
      prefix: /WEB-INF/views/
      suffix: .jsp